# Generated by Django 6.0.6 on 2026-07-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Event title', max_length=30)),
                ('date', models.DateField(help_text='Event date')),
                ('time', models.TimeField(blank=True, help_text='Event time', null=True)),
                ('attendants', models.IntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('description', models.TextField(blank=True, help_text='Event description', null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, help_text='Event charge', max_digits=10, null=True)),
                ('automatic', models.BooleanField(help_text='Apply to all partners')),
                ('validity', models.CharField(blank=True, choices=[('monthly', 'monthly'), ('weekly', 'weekly'), ('yearly', 'yearly')], help_text='Validity', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['date', 'time'],
                'unique_together': {('name', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edition', models.DateTimeField(auto_now_add=True)),
                ('brief', models.TextField()),
                ('description', models.TextField()),
                ('event', models.ForeignKey(blank=True, db_column='event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['-edition'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendees', models.IntegerField(default=1, help_text='Attendees')),
                ('payment', models.DecimalField(decimal_places=2, default=0, help_text='Payment', max_digits=10)),
                ('event', models.ForeignKey(db_column='event', help_text='Event', on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
                ('partner', models.ForeignKey(db_column='partner', help_text='Partner', on_delete=django.db.models.deletion.DO_NOTHING, to='partners.partner')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
                'db_table': 'share',
                'ordering': ['-event', 'partner'],
                'unique_together': {('partner', 'event')},
            },
        ),
    ]
