# Generated by Django 6.0.3 on 2026-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Event title", max_length=30)),
                ("date", models.DateField(help_text="Event date")),
                (
                    "time",
                    models.TimeField(blank=True, help_text="Event time", null=True),
                ),
                ("attendants", models.IntegerField(blank=True, null=True)),
                ("creation", models.DateTimeField(help_text="Creation date")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Event description", null=True
                    ),
                ),
                (
                    "charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Event charge",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["-date", "-time"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edition", models.DateTimeField()),
                ("brief", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "db_table": "news",
                "ordering": ["-edition"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendees",
                    models.IntegerField(blank=True, help_text="Attendees", null=True),
                ),
                (
                    "payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Payment",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share",
                "verbose_name_plural": "Shares",
                "db_table": "share",
                "ordering": ["-event", "partner"],
                "managed": False,
            },
        ),
    ]
