# Generated by Django 6.0.6 on 2026-06-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ['date', 'time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
