# Generated by Django 6.0.3 on 2026-03-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounting",
            options={"managed": False, "ordering": ["-date", "concept"]},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"managed": False, "ordering": ["-date", "-time"]},
        ),
        migrations.AlterModelOptions(
            name="share",
            options={"managed": False, "ordering": ["-event", "partner"]},
        ),
    ]
