# Generated by Django 6.0.3 on 2026-04-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounting",
            options={
                "managed": False,
                "ordering": ["-date", "concept"],
                "permissions": (
                    ("can_see_accounting", "Can see the accounting list."),
                ),
                "verbose_name": "Accounting",
                "verbose_name_plural": "Accounting",
            },
        ),
    ]
