# Generated by Django 6.0.3 on 2026-03-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_accounting_options_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounting",
            options={
                "managed": False,
                "ordering": ["-date", "concept"],
                "verbose_name": "Accounting",
                "verbose_name_plural": "Accounting",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "managed": False,
                "ordering": ["-date", "-time"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="share",
            options={
                "managed": False,
                "ordering": ["-event", "partner"],
                "verbose_name": "Share",
                "verbose_name_plural": "Shares",
            },
        ),
    ]
