# Generated by Django 6.0.3 on 2026-05-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_accounting_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounting",
            options={
                "managed": False,
                "ordering": ["-date", "concept"],
                "verbose_name": "Accounting",
                "verbose_name_plural": "Accounting",
            },
        ),
    ]
