# Generated by Django 6.0.3 on 2026-04-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
