# Generated by Django 6.0.6 on 2026-07-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='City', max_length=35)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Country', max_length=35, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Address', max_length=30)),
                ('zip_code', models.CharField(help_text='ZIP Code', max_length=8)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=10, null=True)),
                ('city', models.ForeignKey(db_column='city', help_text='City', on_delete=django.db.models.deletion.DO_NOTHING, to='partners.city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(choices=[('identification_1', 'identification_1'), ('identification_2', 'identification_2'), ('identification_3', 'identification_3')], default='identification_1', max_length=20, verbose_name='Identification')),
                ('id_number', models.IntegerField(help_text='Identification number', verbose_name='Identification number')),
                ('social_security', models.CharField(blank=True, help_text='Social Security', max_length=15, null=True, unique=True, verbose_name='Social Security')),
                ('last_name', models.CharField(help_text='Last name', max_length=30)),
                ('first_name', models.CharField(help_text='First and middle name', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthdate', models.DateField(help_text='Birthdate')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=15)),
                ('cellphone', models.CharField(blank=True, help_text='Cell phone number', max_length=10, null=True)),
                ('address', models.ForeignKey(db_column='address', help_text='Address', on_delete=django.db.models.deletion.DO_NOTHING, to='partners.address')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('identification', 'id_number')},
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_number', models.IntegerField(help_text='Partner number', unique=True)),
                ('incorporation', models.DateField(help_text='Incorporation date')),
                ('position', models.CharField(choices=[('position_1', 'position_1'), ('position_2', 'position_2'), ('position_3', 'position_3'), ('position_4', 'position_4')], default='position_1', max_length=15)),
                ('status', models.CharField(choices=[('status_1', 'status_1'), ('status_2', 'status_2'), ('status_3', 'status_3')], default='status_1', max_length=15)),
                ('person', models.ForeignKey(db_column='person', help_text='Person', on_delete=django.db.models.deletion.DO_NOTHING, to='partners.person')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners',
                'ordering': ['partner_number'],
                'permissions': (('management', 'Can manage the system'),),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='State', max_length=35)),
                ('country', models.ForeignKey(db_column='country', help_text='Country', on_delete=django.db.models.deletion.DO_NOTHING, to='partners.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='state', help_text='State', on_delete=django.db.models.deletion.DO_NOTHING, to='partners.state'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
