# Generated by Django 6.0.6 on 2026-06-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='doc_number',
            field=models.IntegerField(help_text='Document number', verbose_name='Document number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='doc_type',
            field=models.CharField(choices=[('document_1', 'document_1'), ('document_2', 'document_2'), ('document_3', 'document_3')], default='document_1', max_length=20, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_security',
            field=models.CharField(blank=True, help_text='Social Security', max_length=15, null=True, unique=True, verbose_name='Social Security'),
        ),
    ]
