# Generated by Django 6.0.6 on 2026-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date')),
                ('concept', models.CharField(help_text='Concept', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Concept detail', null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, help_text='Debit', max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit', max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Accounting',
                'verbose_name_plural': 'Accounting',
                'db_table': 'accounting',
                'ordering': ['-date', 'concept'],
            },
        ),
    ]
