# Generated by Django 6.0.3 on 2026-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(help_text="Address", max_length=30)),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "addresses",
                "ordering": ["address"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="City", max_length=35)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "cities",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Country", max_length=35, unique=True),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "countries",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner_number",
                    models.IntegerField(help_text="Partner number", unique=True),
                ),
                ("incorporation", models.DateField(help_text="Incorporation date")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("position_1", "position_1"),
                            ("position_2", "position_2"),
                            ("position_3", "position_3"),
                            ("position_4", "position_4"),
                        ],
                        default="position_1",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("status_1", "status_1"),
                            ("status_2", "status_2"),
                            ("status_3", "status_3"),
                        ],
                        default="status_1",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "db_table": "partners",
                "ordering": ["partner_number"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("document_1", "document_1"),
                            ("document_2", "document_2"),
                            ("document_3", "document_3"),
                        ],
                        default="document_1",
                        max_length=20,
                    ),
                ),
                ("doc_number", models.IntegerField(help_text="Document number")),
                (
                    "social_security",
                    models.CharField(
                        blank=True,
                        help_text="Social Security",
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("last_name", models.CharField(help_text="Last name", max_length=30)),
                (
                    "first_name",
                    models.CharField(help_text="First and middle name", max_length=30),
                ),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("birthdate", models.DateField(help_text="Birthdate")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("other", "other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "cellphone",
                    models.CharField(
                        blank=True,
                        help_text="Cell phone number",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
                "db_table": "persons",
                "ordering": ["last_name", "first_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="State", max_length=35)),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "states",
                "ordering": ["name"],
                "managed": False,
            },
        ),
    ]
