# Generated by Django 6.0.3 on 2026-03-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"managed": False, "ordering": ["address"]},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="doctype",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={"managed": False, "ordering": ["partner_number"]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"managed": False, "ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="sex",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"managed": False, "ordering": ["name"]},
        ),
    ]
