# Generated by Django 6.0.3 on 2026-05-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "managed": False,
                "ordering": ["partner_number"],
                "permissions": (("management", "Can manage the system"),),
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
    ]
