# Generated by Django 6.0.3 on 2026-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_address_options_alter_city_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Partner Status",
                "verbose_name_plural": "Partner States",
                "db_table": "partner_status",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="address",
            options={
                "managed": False,
                "ordering": ["address"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterModelOptions(
            name="doctype",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "Doc Type",
                "verbose_name_plural": "Doc Types",
            },
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={
                "managed": False,
                "ordering": ["partner_number"],
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "managed": False,
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.AlterModelOptions(
            name="sex",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "Sex",
                "verbose_name_plural": "Sexes",
            },
        ),
        migrations.AlterModelOptions(
            name="state",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "State",
                "verbose_name_plural": "States",
            },
        ),
    ]
