# Generated by Django 6.0.6 on 2026-06-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Username', max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
