DROP DATABASE IF EXISTS sbms;
DROP ROLE IF EXISTS sbmsapp;

CREATE DATABASE sbms;
CREATE ROLE sbmsapp WITH LOGIN PASSWORD 'sbmsapp123';
ALTER DATABASE sbms OWNER TO sbmsapp;
ALTER ROLE sbmsapp CREATEDB;
